### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by ttop5** [ttop5/to-be-slack#2]
- [ ] SEO;
- [ ] 菜单搜索；
- [ ] 菜单根据热度排序；
- [ ] 菜单定制优化；
- [ ] 热榜列表添加描述（待定）;
- [ ] 记住浏览的菜单位置（主要针对Chrome拓展）；
- [x] 完成Web端基本功能；
- [x] 支持Chrome拓展；
- [x] 支持PWA；

**Comment by timeromantic** [comment]
- [ ] 备案tophub.fun添加多个域名

**Comment by timeromantic** [comment]
- [ ] 部署到服务器，避免托管github速度太慢

**Comment by ttop5** [comment]
- [ ] 更换图标

**Comment by ttop5** [comment]
[ ] 热点摘要部分优化

**Comment by ttop5** [comment]
- [ ] PWA 白屏问题

**Comment by ttop5** [comment]
- [ ] 菜单分类

**Comment by maicong** [comment]
能否增加个菜单排序功能？

**Comment by ttop5** [comment]
@maicong 感谢建议，我们将在后续优化中考虑加入此功能哈

**Comment by maicong** [comment]
@ttop5 可以弄个拖动排序，完后生成一份样式保存在 localStorage 就行，我用 stylish 按照我的喜好排序了。
参考代码：
```css
.q-list.rounded-borders {
    display: flex;
    flex-direction: column
}
a[href="#/?id=60"],
a[href="#/?id=61"],
a[href="#/?id=83"],
a[href="#/?id=86"],
a[href="#/?id=104"] {
    display: none
}
a[href="#/?id=1"] {
    order: 11
}
a[href="#/?id=59"] {
    order: 22
}
a[href="#/?id=58"] {
    order: 33
}
a[href="#/?id=56"] {
    order: 44
}
a[href="#/?id=2"] {
    order: 55
}
a[href="#/?id=8"] {
    order: 56
}
a[href="#/?id=6"] {
    order: 66
}
a[href="#/?id=9"] {
    order: 77
}
a[href="#/?id=7"] {
    order: 88
}
a[href="#/?id=111"] {
    order: 99
}
```
